### ISSUE TITLE
Add Social Media (no OAuth?)

### ISSUE THREAD

**Issue by BenEmdon** [Branch-Bunch/FaceDex#11]
Having a persons twitter/linkedin/facebook/myspace profiles all in one place would be 🙌

**Comment by JackyChiu** [comment]
I think you meant to say OAuth

**Comment by JackyChiu** [comment]
How I imagine it is that in the choice of enrollment we can have serval buttons to connect with their  twitter/linkedin/facebook, but how should we deal with the case where I "capture" someone on my phone (since Oauth wouldn't be easy then)?

**Comment by BenEmdon** [comment]
OAuth might take the fun out of it because you would have to make them sign in with their accounts (no password completion could make the experience less spontaneous) 😞 What if we just focus on tagging people without signing in and make it so anyone can go and edit the social info stored? Sort of like how Wiki's work (anyone can contribute)

**Comment by JackyChiu** [comment]
I agree that it would take the fun out of it for people tagging, but it would also be quite a hassle to do your social media links yourself

Any ideas to find a middle ground?

**Comment by BenEmdon** [comment]
Reactive search through twitter/github usernames that show up like usernames do in slack? Slack open sourced their keyboard! Not sure how we would do facebook or LinkedIn though (not sure how open their APIs are)

**Comment by JackyChiu** [comment]
I like that idea, is there a way we can have "official" information? Like information that the owner of the face inputted

Ex. What if I want to set my github to @JackyChiu but people keep editing to like @gitgud?

**Comment by BenEmdon** [comment]
Good point ☝️ anyone have a solution to this problem? @VikramBombhi @Abdulwahaab710

**Comment by JackyChiu** [comment]
We might just have to trust in our users

**Comment by BenEmdon** [comment]
lets reopen this when we come back to this project 📕
